version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: payroll-app
    container_name: payroll-app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    environment:
      SERVICE_NAME: payroll-app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
  db:
    image: mysql:5.7
    container_name: payroll-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:

